# Generated by Django 4.2.26 on 2025-11-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeats',
            field=models.BooleanField(default=False),
        ),
    ]
