# Generated by Django 4.2.26 on 2025-11-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_repeats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='repeats',
        ),
    ]
